name = "sveltia-cms-prueba"
main = "src/index.js"
compatibility_date = "2025-08-24"

[vars]
GITHUB_CLIENT_ID = "Ov23lizFauqg5DImQOtf"
GITHUB_CLIENT_SECRET = "623247926278ffbf8bd206f69aeca76c73ebda60"
ALLOWED_DOMAINS = "sebastiandemo.netlify.app"

