name = "sveltia-cms-prueba"
main = "src/index.js"
compatibility_date = "2023-08-24" # poné la fecha actual o una reciente

[vars]
GITHUB_CLIENT_ID = "Ov23lizFauqg5DImQOtf"
GITHUB_CLIENT_SECRET = "623247926278ffbf8bd206f69aeca76c73ebda60"
OAUTH_CALLBACK = "https://sebastiandemo.netlify.app/.netlify/functions/callback"
