name = "sveltia-cms-prueba"
main = "src/index.js"
compatibility_date = "2025-08-24"

[vars]
GITHUB_CLIENT_ID = "Ov23lizFauqg5DImQOtf"
GITHUB_CLIENT_SECRET = "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"
ALLOWED_DOMAINS = "sebastiandemo.netlify.app"
OAUTH_CALLBACK = "https://sveltia-cms-prueba.kitdelanzamientodigital.workers.dev/callback"
