name: Deploy Worker + Admin UI

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      # Instalamos Wrangler globalmente con npm (evitamos pnpm)
      - name: Install Wrangler
        run: npm install -g @cloudflare/wrangler

      # Publicamos tu Worker + site
      - name: Publish to Cloudflare
        run: wrangler publish
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
